var annotated_dup =
[
    [ "Ponca", "namespacePonca.html", [
      [ "internal", "namespacePonca_1_1internal.html", [
        [ "CNCEigen", "structPonca_1_1internal_1_1CNCEigen.html", "structPonca_1_1internal_1_1CNCEigen" ],
        [ "CurvatureEstimatorBase", "classPonca_1_1internal_1_1CurvatureEstimatorBase.html", "classPonca_1_1internal_1_1CurvatureEstimatorBase" ],
        [ "HexagramBase", "structPonca_1_1internal_1_1HexagramBase.html", null ],
        [ "Triangle", "structPonca_1_1internal_1_1Triangle.html", "structPonca_1_1internal_1_1Triangle" ],
        [ "TriangleGenerator", "structPonca_1_1internal_1_1TriangleGenerator.html", null ],
        [ "TriangleGenerator< AvgHexagramGeneration, P >", "structPonca_1_1internal_1_1TriangleGenerator_3_01AvgHexagramGeneration_00_01P_01_4.html", null ],
        [ "TriangleGenerator< HexagramGeneration, P >", "structPonca_1_1internal_1_1TriangleGenerator_3_01HexagramGeneration_00_01P_01_4.html", null ],
        [ "TriangleGenerator< IndependentGeneration, P >", "structPonca_1_1internal_1_1TriangleGenerator_3_01IndependentGeneration_00_01P_01_4.html", null ],
        [ "TriangleGenerator< UniformGeneration, P >", "structPonca_1_1internal_1_1TriangleGenerator_3_01UniformGeneration_00_01P_01_4.html", null ],
        [ "WeingartenCurvatureEstimatorBase", "classPonca_1_1internal_1_1WeingartenCurvatureEstimatorBase.html", "classPonca_1_1internal_1_1WeingartenCurvatureEstimatorBase" ]
      ] ],
      [ "AlgebraicSphere", "classPonca_1_1AlgebraicSphere.html", "classPonca_1_1AlgebraicSphere" ],
      [ "Basket", "classPonca_1_1Basket.html", "classPonca_1_1Basket" ],
      [ "BasketComputeObject", "structPonca_1_1BasketComputeObject.html", "structPonca_1_1BasketComputeObject" ],
      [ "BasketDiff", "classPonca_1_1BasketDiff.html", "classPonca_1_1BasketDiff" ],
      [ "CenteredNeighborhoodFrame", "classPonca_1_1CenteredNeighborhoodFrame.html", "classPonca_1_1CenteredNeighborhoodFrame" ],
      [ "CNC", "classPonca_1_1CNC.html", "classPonca_1_1CNC" ],
      [ "CompactExpWeightKernel", "classPonca_1_1CompactExpWeightKernel.html", "classPonca_1_1CompactExpWeightKernel" ],
      [ "ComputeObject", "structPonca_1_1ComputeObject.html", "structPonca_1_1ComputeObject" ],
      [ "ConstantWeightKernel", "classPonca_1_1ConstantWeightKernel.html", "classPonca_1_1ConstantWeightKernel" ],
      [ "CovarianceFitBase", "classPonca_1_1CovarianceFitBase.html", "classPonca_1_1CovarianceFitBase" ],
      [ "CovarianceFitDer", "classPonca_1_1CovarianceFitDer.html", "classPonca_1_1CovarianceFitDer" ],
      [ "CovarianceLineFitImpl", "classPonca_1_1CovarianceLineFitImpl.html", "classPonca_1_1CovarianceLineFitImpl" ],
      [ "CovariancePlaneDerImpl", "classPonca_1_1CovariancePlaneDerImpl.html", "classPonca_1_1CovariancePlaneDerImpl" ],
      [ "CovariancePlaneFitImpl", "classPonca_1_1CovariancePlaneFitImpl.html", "classPonca_1_1CovariancePlaneFitImpl" ],
      [ "CurvatureEstimator", "classPonca_1_1CurvatureEstimator.html", "classPonca_1_1CurvatureEstimator" ],
      [ "CurvatureEstimatorDer", "classPonca_1_1CurvatureEstimatorDer.html", "classPonca_1_1CurvatureEstimatorDer" ],
      [ "DistWeightFunc", "classPonca_1_1DistWeightFunc.html", "classPonca_1_1DistWeightFunc" ],
      [ "DryFit", "classPonca_1_1DryFit.html", "classPonca_1_1DryFit" ],
      [ "FundamentalFormWeingartenEstimator", "classPonca_1_1FundamentalFormWeingartenEstimator.html", "classPonca_1_1FundamentalFormWeingartenEstimator" ],
      [ "GaussianWeightKernel", "classPonca_1_1GaussianWeightKernel.html", "classPonca_1_1GaussianWeightKernel" ],
      [ "GlobalNeighborhoodFrame", "classPonca_1_1GlobalNeighborhoodFrame.html", "classPonca_1_1GlobalNeighborhoodFrame" ],
      [ "GLSDer", "classPonca_1_1GLSDer.html", "classPonca_1_1GLSDer" ],
      [ "GLSParam", "classPonca_1_1GLSParam.html", "classPonca_1_1GLSParam" ],
      [ "hasFirstFundamentalForm", "structPonca_1_1hasFirstFundamentalForm.html", null ],
      [ "hasFirstFundamentalForm< T, std::void_t< decltype(std::declval< T >().firstFundamentalForm())> >", "structPonca_1_1hasFirstFundamentalForm_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3c934b077c941f2ac88d2ec4e8e15ad41.html", null ],
      [ "hasNormal", "structPonca_1_1hasNormal.html", null ],
      [ "hasNormal< T, std::void_t< decltype(std::declval< T >().normal())> >", "structPonca_1_1hasNormal_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01T_01_4_07_08_8normal_07_08_08_4_01_4.html", null ],
      [ "HeightField", "classPonca_1_1HeightField.html", "classPonca_1_1HeightField" ],
      [ "IndexSquaredDistance", "structPonca_1_1IndexSquaredDistance.html", "structPonca_1_1IndexSquaredDistance" ],
      [ "KdTree", "structPonca_1_1KdTree.html", null ],
      [ "KdTreeBase", "classPonca_1_1KdTreeBase.html", "classPonca_1_1KdTreeBase" ],
      [ "KdTreeCustomizableNode", "classPonca_1_1KdTreeCustomizableNode.html", "classPonca_1_1KdTreeCustomizableNode" ],
      [ "KdTreeDefaultInnerNode", "structPonca_1_1KdTreeDefaultInnerNode.html", null ],
      [ "KdTreeDefaultLeafNode", "structPonca_1_1KdTreeDefaultLeafNode.html", null ],
      [ "KdTreeDefaultNode", "structPonca_1_1KdTreeDefaultNode.html", null ],
      [ "KdTreeDefaultTraits", "structPonca_1_1KdTreeDefaultTraits.html", "structPonca_1_1KdTreeDefaultTraits" ],
      [ "KdTreeDense", "structPonca_1_1KdTreeDense.html", null ],
      [ "KdTreeDenseBase", "classPonca_1_1KdTreeDenseBase.html", "classPonca_1_1KdTreeDenseBase" ],
      [ "KdTreeKNearestIterator", "classPonca_1_1KdTreeKNearestIterator.html", "classPonca_1_1KdTreeKNearestIterator" ],
      [ "KdTreeKNearestQueryBase", "classPonca_1_1KdTreeKNearestQueryBase.html", "classPonca_1_1KdTreeKNearestQueryBase" ],
      [ "KdTreeNearestIterator", "classPonca_1_1KdTreeNearestIterator.html", "classPonca_1_1KdTreeNearestIterator" ],
      [ "KdTreeNearestQueryBase", "classPonca_1_1KdTreeNearestQueryBase.html", "classPonca_1_1KdTreeNearestQueryBase" ],
      [ "KdTreePointerTraits", "structPonca_1_1KdTreePointerTraits.html", "structPonca_1_1KdTreePointerTraits" ],
      [ "KdTreeQuery", "classPonca_1_1KdTreeQuery.html", "classPonca_1_1KdTreeQuery" ],
      [ "KdTreeRangeIterator", "classPonca_1_1KdTreeRangeIterator.html", "classPonca_1_1KdTreeRangeIterator" ],
      [ "KdTreeRangeQueryBase", "classPonca_1_1KdTreeRangeQueryBase.html", "classPonca_1_1KdTreeRangeQueryBase" ],
      [ "KdTreeSparse", "structPonca_1_1KdTreeSparse.html", null ],
      [ "KdTreeSparseBase", "classPonca_1_1KdTreeSparseBase.html", "classPonca_1_1KdTreeSparseBase" ],
      [ "KNearestIndexQuery", "group__spatialpartitioning.html#structPonca_1_1KNearestIndexQuery", "group__spatialpartitioning_structPonca_1_1KNearestIndexQuery" ],
      [ "KNearestPointQuery", "group__spatialpartitioning.html#structPonca_1_1KNearestPointQuery", "group__spatialpartitioning_structPonca_1_1KNearestPointQuery" ],
      [ "KnnGraphBase", "classPonca_1_1KnnGraphBase.html", "classPonca_1_1KnnGraphBase" ],
      [ "KnnGraphDefaultTraits", "structPonca_1_1KnnGraphDefaultTraits.html", "structPonca_1_1KnnGraphDefaultTraits" ],
      [ "KnnGraphKNearestQuery", "classPonca_1_1KnnGraphKNearestQuery.html", "classPonca_1_1KnnGraphKNearestQuery" ],
      [ "KnnGraphRangeIterator", "classPonca_1_1KnnGraphRangeIterator.html", "classPonca_1_1KnnGraphRangeIterator" ],
      [ "KnnGraphRangeQuery", "classPonca_1_1KnnGraphRangeQuery.html", "classPonca_1_1KnnGraphRangeQuery" ],
      [ "limited_priority_queue", "classPonca_1_1limited__priority__queue.html", null ],
      [ "Line", "classPonca_1_1Line.html", "classPonca_1_1Line" ],
      [ "MeanNormal", "classPonca_1_1MeanNormal.html", "classPonca_1_1MeanNormal" ],
      [ "MeanNormalDer", "classPonca_1_1MeanNormalDer.html", "classPonca_1_1MeanNormalDer" ],
      [ "MeanPlaneFitImpl", "classPonca_1_1MeanPlaneFitImpl.html", "classPonca_1_1MeanPlaneFitImpl" ],
      [ "MeanPosition", "classPonca_1_1MeanPosition.html", "classPonca_1_1MeanPosition" ],
      [ "MeanPositionDer", "classPonca_1_1MeanPositionDer.html", "classPonca_1_1MeanPositionDer" ],
      [ "MlsSphereFitDer", "classPonca_1_1MlsSphereFitDer.html", "classPonca_1_1MlsSphereFitDer" ],
      [ "MongePatch", "classPonca_1_1MongePatch.html", "classPonca_1_1MongePatch" ],
      [ "MongePatchQuadraticFitImpl", "classPonca_1_1MongePatchQuadraticFitImpl.html", "classPonca_1_1MongePatchQuadraticFitImpl" ],
      [ "MongePatchRestrictedQuadraticFitImpl", "classPonca_1_1MongePatchRestrictedQuadraticFitImpl.html", "classPonca_1_1MongePatchRestrictedQuadraticFitImpl" ],
      [ "NearestIndexQuery", "group__spatialpartitioning.html#structPonca_1_1NearestIndexQuery", "group__spatialpartitioning_structPonca_1_1NearestIndexQuery" ],
      [ "NearestPointQuery", "group__spatialpartitioning.html#structPonca_1_1NearestPointQuery", "group__spatialpartitioning_structPonca_1_1NearestPointQuery" ],
      [ "NeighborFilterStoreNormal", "classPonca_1_1NeighborFilterStoreNormal.html", "classPonca_1_1NeighborFilterStoreNormal" ],
      [ "NormalDerivativeWeingartenEstimator", "classPonca_1_1NormalDerivativeWeingartenEstimator.html", "classPonca_1_1NormalDerivativeWeingartenEstimator" ],
      [ "NoWeightFuncBase", "classPonca_1_1NoWeightFuncBase.html", "classPonca_1_1NoWeightFuncBase" ],
      [ "OrientedSphereDerImpl", "classPonca_1_1OrientedSphereDerImpl.html", "classPonca_1_1OrientedSphereDerImpl" ],
      [ "OrientedSphereFitImpl", "classPonca_1_1OrientedSphereFitImpl.html", "classPonca_1_1OrientedSphereFitImpl" ],
      [ "Plane", "classPonca_1_1Plane.html", "classPonca_1_1Plane" ],
      [ "PointPosition", "classPonca_1_1PointPosition.html", "classPonca_1_1PointPosition" ],
      [ "PointPositionNormal", "classPonca_1_1PointPositionNormal.html", "classPonca_1_1PointPositionNormal" ],
      [ "PointPositionNormalBinding", "classPonca_1_1PointPositionNormalBinding.html", "classPonca_1_1PointPositionNormalBinding" ],
      [ "PointPositionNormalLazyBinding", "classPonca_1_1PointPositionNormalLazyBinding.html", "classPonca_1_1PointPositionNormalLazyBinding" ],
      [ "PolynomialSmoothWeightKernel", "classPonca_1_1PolynomialSmoothWeightKernel.html", "classPonca_1_1PolynomialSmoothWeightKernel" ],
      [ "PrimitiveBase", "classPonca_1_1PrimitiveBase.html", "classPonca_1_1PrimitiveBase" ],
      [ "PrimitiveDer", "classPonca_1_1PrimitiveDer.html", "classPonca_1_1PrimitiveDer" ],
      [ "QuadraticHeightField", "classPonca_1_1QuadraticHeightField.html", "classPonca_1_1QuadraticHeightField" ],
      [ "Query", "group__spatialpartitioning.html#structPonca_1_1Query", "group__spatialpartitioning_structPonca_1_1Query" ],
      [ "QueryInput", "group__spatialpartitioning.html#structPonca_1_1QueryInput", "group__spatialpartitioning_structPonca_1_1QueryInput" ],
      [ "QueryInputBase", "group__spatialpartitioning.html#structPonca_1_1QueryInputBase", null ],
      [ "QueryInputIsIndex", "group__spatialpartitioning.html#structPonca_1_1QueryInputIsIndex", "group__spatialpartitioning_structPonca_1_1QueryInputIsIndex" ],
      [ "QueryInputIsPosition", "group__spatialpartitioning.html#structPonca_1_1QueryInputIsPosition", "group__spatialpartitioning_structPonca_1_1QueryInputIsPosition" ],
      [ "QueryOutputBase", "group__spatialpartitioning.html#structPonca_1_1QueryOutputBase", null ],
      [ "QueryOutputIsKNearest", "group__spatialpartitioning.html#structPonca_1_1QueryOutputIsKNearest", "group__spatialpartitioning_structPonca_1_1QueryOutputIsKNearest" ],
      [ "QueryOutputIsNearest", "group__spatialpartitioning.html#structPonca_1_1QueryOutputIsNearest", "group__spatialpartitioning_structPonca_1_1QueryOutputIsNearest" ],
      [ "QueryOutputIsRange", "group__spatialpartitioning.html#structPonca_1_1QueryOutputIsRange", "group__spatialpartitioning_structPonca_1_1QueryOutputIsRange" ],
      [ "RangeIndexQuery", "group__spatialpartitioning.html#structPonca_1_1RangeIndexQuery", "group__spatialpartitioning_structPonca_1_1RangeIndexQuery" ],
      [ "RangePointQuery", "group__spatialpartitioning.html#structPonca_1_1RangePointQuery", "group__spatialpartitioning_structPonca_1_1RangePointQuery" ],
      [ "RestrictedQuadraticHeightField", "classPonca_1_1RestrictedQuadraticHeightField.html", "classPonca_1_1RestrictedQuadraticHeightField" ],
      [ "SingularWeightKernel", "classPonca_1_1SingularWeightKernel.html", "classPonca_1_1SingularWeightKernel" ],
      [ "SmoothWeightKernel", "classPonca_1_1SmoothWeightKernel.html", "classPonca_1_1SmoothWeightKernel" ],
      [ "SphereFitImpl", "classPonca_1_1SphereFitImpl.html", "classPonca_1_1SphereFitImpl" ],
      [ "Stack", "classPonca_1_1Stack.html", "classPonca_1_1Stack" ],
      [ "StaticKdTree", "structPonca_1_1StaticKdTree.html", null ],
      [ "StaticKdTreeBase", "classPonca_1_1StaticKdTreeBase.html", "classPonca_1_1StaticKdTreeBase" ],
      [ "UnorientedSphereDerImpl", "classPonca_1_1UnorientedSphereDerImpl.html", "classPonca_1_1UnorientedSphereDerImpl" ],
      [ "UnorientedSphereFitImpl", "classPonca_1_1UnorientedSphereFitImpl.html", "classPonca_1_1UnorientedSphereFitImpl" ],
      [ "WeingartenCurvatureEstimator", "structPonca_1_1WeingartenCurvatureEstimator.html", "structPonca_1_1WeingartenCurvatureEstimator" ],
      [ "WeingartenCurvatureEstimatorDer", "structPonca_1_1WeingartenCurvatureEstimatorDer.html", "structPonca_1_1WeingartenCurvatureEstimatorDer" ],
      [ "WendlandWeightKernel", "classPonca_1_1WendlandWeightKernel.html", "classPonca_1_1WendlandWeightKernel" ]
    ] ]
];