var searchData=
[
  ['quadraticheightfield_0',['quadraticheightfield',['../classPonca_1_1QuadraticHeightField.html',1,'Ponca::QuadraticHeightField&lt; DataPoint, _NFilter, T &gt;'],['../classPonca_1_1RestrictedQuadraticHeightField.html#a497eda4357b55f74f3d755b5f978d3bb',1,'Ponca::RestrictedQuadraticHeightField::quadraticHeightField() const'],['../classPonca_1_1RestrictedQuadraticHeightField.html#abaebd8709ceb1fe834a9bba3de12c99f',1,'Ponca::RestrictedQuadraticHeightField::quadraticHeightField()'],['../classPonca_1_1QuadraticHeightField.html#a9547a07f49c2739c823ad8613d76af09',1,'Ponca::QuadraticHeightField::quadraticHeightField() const'],['../classPonca_1_1QuadraticHeightField.html#aa8170554d221efe1383a244ee184bb6b',1,'Ponca::QuadraticHeightField::quadraticHeightField()'],['../classPonca_1_1QuadraticHeightField.html#a768ecf29239d53ac4fe03f4a7eebc1c1',1,'Ponca::QuadraticHeightField::QuadraticHeightField()']]],
  ['queries_1',['queries',['../example_cu_kdtree_page.html',1,'Object-space Curvature using Cuda/C++ and KdTree queries'],['../spatialpartitioning.html#spatialpartitioning_knngraph_usage_queries',1,'Queries'],['../spatialpartitioning.html#spatialpartitioning_kdtree_usage_queries',1,'Queries'],['../spatialpartitioning.html#spatialpartitioning_intro_queries',1,'Queries']]],
  ['query_2',['query',['../group__spatialpartitioning.html#structPonca_1_1Query',1,'Ponca::Query&lt; Input_, Output_ &gt;'],['../group__spatialpartitioning.html#ae94b0fc73e9730e3f71dbf655d04b028',1,'Ponca::Query::Query(const typename QueryInType::InputType &amp;in)'],['../group__spatialpartitioning.html#a643f2783821066d76804a9601a593ed8',1,'Ponca::Query::Query(const typename QueryOutType::OutputParameter &amp;outParam, const typename QueryInType::InputType &amp;in)']]],
  ['queryinput_3',['queryinput',['../group__spatialpartitioning.html#structPonca_1_1QueryInput',1,'Ponca::QueryInput&lt; InputType_ &gt;'],['../group__spatialpartitioning.html#a00cb8f43f8e4ab6a20cb8f24dbc13b3e',1,'Ponca::QueryInput::QueryInput()']]],
  ['queryinput_3c_20datapoint_3a_3avectortype_20_3e_4',['QueryInput&lt; DataPoint::VectorType &gt;',['../group__spatialpartitioning.html',1,'Ponca']]],
  ['queryinput_3c_20index_20_3e_5',['QueryInput&lt; Index &gt;',['../group__spatialpartitioning.html',1,'Ponca']]],
  ['queryinputbase_6',['QueryInputBase',['../group__spatialpartitioning.html#structPonca_1_1QueryInputBase',1,'Ponca']]],
  ['queryinputisindex_7',['queryinputisindex',['../group__spatialpartitioning.html#structPonca_1_1QueryInputIsIndex',1,'Ponca::QueryInputIsIndex&lt; Index &gt;'],['../group__spatialpartitioning.html#af31a7ce6e6c6eb6818906ac5074f6711',1,'Ponca::QueryInputIsIndex::QueryInputIsIndex()']]],
  ['queryinputisposition_8',['queryinputisposition',['../group__spatialpartitioning.html#a4188c9adc504006a9e0ed899a1dbf18a',1,'Ponca::QueryInputIsPosition::QueryInputIsPosition()'],['../group__spatialpartitioning.html#structPonca_1_1QueryInputIsPosition',1,'Ponca::QueryInputIsPosition&lt; DataPoint &gt;']]],
  ['queryintype_9',['QueryInType',['../group__spatialpartitioning.html#a8510a6300c87c52a9920fb4121a928be',1,'Ponca::Query']]],
  ['queryoutputbase_10',['QueryOutputBase',['../group__spatialpartitioning.html#structPonca_1_1QueryOutputBase',1,'Ponca']]],
  ['queryoutputisknearest_11',['queryoutputisknearest',['../group__spatialpartitioning.html#aef1ccada39dedc8f23391ff62be0d2ab',1,'Ponca::QueryOutputIsKNearest::QueryOutputIsKNearest()'],['../group__spatialpartitioning.html#structPonca_1_1QueryOutputIsKNearest',1,'Ponca::QueryOutputIsKNearest&lt; Index, Scalar, MAX_KNN_SIZE &gt;']]],
  ['queryoutputisnearest_12',['queryoutputisnearest',['../group__spatialpartitioning.html#structPonca_1_1QueryOutputIsNearest',1,'Ponca::QueryOutputIsNearest&lt; Index, Scalar &gt;'],['../group__spatialpartitioning.html#a90c27675efb1cf5e3d3350805bae7d36',1,'Ponca::QueryOutputIsNearest::QueryOutputIsNearest()']]],
  ['queryoutputisrange_13',['queryoutputisrange',['../group__spatialpartitioning.html#a38f2eff46a5a58623d4208aa5a7d3d2c',1,'Ponca::QueryOutputIsRange::QueryOutputIsRange()'],['../group__spatialpartitioning.html#structPonca_1_1QueryOutputIsRange',1,'Ponca::QueryOutputIsRange&lt; Index, Scalar &gt;']]],
  ['queryouttype_14',['QueryOutType',['../group__spatialpartitioning.html#a96da2b09ce5746acad33e35c46c5d035',1,'Ponca::Query']]],
  ['queue_15',['queue',['../group__spatialpartitioning.html#a4e8e59f71edf835cd2c8abba02a5c8f1',1,'Ponca::QueryOutputIsKNearest::Queue'],['../group__spatialpartitioning.html#ae5af90d3ef429ec3b77ba2ebbd39078a',1,'Ponca::QueryOutputIsKNearest::queue()']]]
];
