var searchData=
[
  ['k1_0',['k1',['../classPonca_1_1CurvatureEstimatorBase.html#a877d9ead3ac1045ebbd94d1045fc38c6',1,'Ponca::CurvatureEstimatorBase']]],
  ['k1direction_1',['k1Direction',['../classPonca_1_1CurvatureEstimatorBase.html#afb9830d3cd98bbf9b4c715bd6c6875a8',1,'Ponca::CurvatureEstimatorBase']]],
  ['k2_2',['k2',['../classPonca_1_1CurvatureEstimatorBase.html#a4be6423b13b5ffe0cef33cddbb7d7cfc',1,'Ponca::CurvatureEstimatorBase']]],
  ['k2direction_3',['k2Direction',['../classPonca_1_1CurvatureEstimatorBase.html#a8dad959069ee07f91a51ddb44eed9218',1,'Ponca::CurvatureEstimatorBase']]],
  ['kappa_4',['kappa',['../classPonca_1_1GLSParam.html#af50e8af7862b3dcb185ff21c573fa784',1,'Ponca::GLSParam']]],
  ['kappa_5fnormalized_5',['kappa_normalized',['../classPonca_1_1GLSParam.html#abec25f5fc1914516c36082df250ee50e',1,'Ponca::GLSParam']]],
  ['kdtree_6',['KdTree',['../namespacePonca.html#abdeec7124bd618c93bfd5374d56e7155',1,'Ponca']]],
  ['kdtreebase_7',['KdTreeBase',['../classPonca_1_1KdTreeBase.html#abda91fbc025f6e2f7d2bb79db05f18b3',1,'Ponca::KdTreeBase::KdTreeBase(PointUserContainer &amp;&amp;points, IndexUserContainer sampling)'],['../classPonca_1_1KdTreeBase.html#a6d6d808e01a80764edcc718da9829a46',1,'Ponca::KdTreeBase::KdTreeBase(PointUserContainer &amp;&amp;points)'],['../classPonca_1_1KdTreeBase.html#ab03cf0da552980bd25d27952b9ee3886',1,'Ponca::KdTreeBase::KdTreeBase()'],['../classPonca_1_1KdTreeBase.html',1,'Ponca::KdTreeBase&lt; Traits &gt;']]],
  ['kdtreedefaultinnernode_8',['KdTreeDefaultInnerNode',['../structPonca_1_1KdTreeDefaultInnerNode.html',1,'Ponca']]],
  ['kdtreedefaultleafnode_9',['KdTreeDefaultLeafNode',['../structPonca_1_1KdTreeDefaultLeafNode.html',1,'Ponca']]],
  ['kdtreedefaultleafnode_3c_20index_2c_20leafsizetype_20_3e_10',['KdTreeDefaultLeafNode&lt; Index, LeafSizeType &gt;',['../structPonca_1_1KdTreeDefaultLeafNode.html',1,'Ponca']]],
  ['kdtreedefaultnode_11',['KdTreeDefaultNode',['../structPonca_1_1KdTreeDefaultNode.html',1,'Ponca']]],
  ['kdtreedefaulttraits_12',['KdTreeDefaultTraits',['../structPonca_1_1KdTreeDefaultTraits.html',1,'Ponca']]],
  ['kdtreeknearestindexquery_13',['KdTreeKNearestIndexQuery',['../classPonca_1_1KdTreeKNearestIndexQuery.html',1,'Ponca']]],
  ['kdtreeknearestiterator_14',['KdTreeKNearestIterator',['../classPonca_1_1KdTreeKNearestIterator.html',1,'Ponca']]],
  ['kdtreeknearestpointquery_15',['KdTreeKNearestPointQuery',['../classPonca_1_1KdTreeKNearestPointQuery.html',1,'Ponca']]],
  ['kdtreenearestindexquery_16',['KdTreeNearestIndexQuery',['../classPonca_1_1KdTreeNearestIndexQuery.html',1,'Ponca']]],
  ['kdtreenearestiterator_17',['KdTreeNearestIterator',['../classPonca_1_1KdTreeNearestIterator.html',1,'Ponca']]],
  ['kdtreenearestpointquery_18',['KdTreeNearestPointQuery',['../classPonca_1_1KdTreeNearestPointQuery.html',1,'Ponca']]],
  ['kdtreequery_19',['KdTreeQuery',['../classPonca_1_1KdTreeQuery.html',1,'Ponca']]],
  ['kdtreerangeindexquery_20',['KdTreeRangeIndexQuery',['../classPonca_1_1KdTreeRangeIndexQuery.html',1,'Ponca']]],
  ['kdtreerangeiterator_21',['KdTreeRangeIterator',['../classPonca_1_1KdTreeRangeIterator.html',1,'Ponca']]],
  ['kdtreerangepointquery_22',['KdTreeRangePointQuery',['../classPonca_1_1KdTreeRangePointQuery.html',1,'Ponca']]],
  ['kmean_23',['kMean',['../classPonca_1_1CurvatureEstimatorBase.html#a2806aae38a187798de67d5eb38771c50',1,'Ponca::CurvatureEstimatorBase::kMean()'],['../classPonca_1_1MongePatch.html#a577334b5f0eb551c969135e70b1d849e',1,'Ponca::MongePatch::kMean()']]],
  ['knearestindexquery_24',['KNearestIndexQuery',['../group__spatialpartitioning.html#structPonca_1_1KNearestIndexQuery',1,'Ponca']]],
  ['knearestindexquery_3c_20traits_3a_3aindextype_2c_20traits_3a_3adatapoint_3a_3ascalar_20_3e_25',['KNearestIndexQuery&lt; Traits::IndexType, Traits::DataPoint::Scalar &gt;',['../group__spatialpartitioning.html',1,'Ponca']]],
  ['knearestpointquery_26',['KNearestPointQuery',['../group__spatialpartitioning.html#structPonca_1_1KNearestPointQuery',1,'Ponca']]],
  ['knearestpointquery_3c_20traits_3a_3aindextype_2c_20traits_3a_3adatapoint_20_3e_27',['KNearestPointQuery&lt; Traits::IndexType, Traits::DataPoint &gt;',['../group__spatialpartitioning.html',1,'Ponca']]]
];
