var searchData=
[
  ['k_0',['k',['../classPonca_1_1KnnGraphBase.html#a88878dc3a1b39079a2d20c61c15fee6c',1,'Ponca::KnnGraphBase']]],
  ['kappa_1',['kappa',['../classPonca_1_1GLSParam.html#a3967bba6e1b7cab5a9c7f7f8c0232ec8',1,'Ponca::GLSParam']]],
  ['kappa_5fnormalized_2',['kappa_normalized',['../classPonca_1_1GLSParam.html#a5bb1c9ad3d34f76a2d634abd4da428df',1,'Ponca::GLSParam']]],
  ['kdtree_3',['kdtree',['../spatialpartitioning.html#spatialpartitioning_kdtree_extending',1,'Extending KdTree'],['../spatialpartitioning.html#spatialpartitioning_kdtree',1,'KdTree'],['../structPonca_1_1KdTree.html',1,'Ponca::KdTree&lt; DataPoint &gt;']]],
  ['kdtree_20and_20kdtreebase_4',['Usage of the convenience classes KdTree and KdTreeBase',['../spatialpartitioning.html#spatialpartitioning_kdtree_usage_which_class',1,'']]],
  ['kdtree_20apis_5',['Comparison between Nanoflann and Ponca KdTree APIs',['../example_cxx_nanoflann_page.html',1,'example_page']]],
  ['kdtreebase_6',['kdtreebase',['../classPonca_1_1KdTreeBase.html',1,'Ponca::KdTreeBase&lt; Traits &gt;'],['../spatialpartitioning.html#spatialpartitioning_kdtree_usage_which_class',1,'Usage of the convenience classes KdTree and KdTreeBase']]],
  ['kdtreebase_3c_20kdtreedefaulttraits_3c_20datapoint_20_3e_20_3e_7',['KdTreeBase&lt; KdTreeDefaultTraits&lt; DataPoint &gt; &gt;',['../classPonca_1_1KdTreeBase.html',1,'Ponca']]],
  ['kdtreecustomizablenode_8',['KdTreeCustomizableNode',['../classPonca_1_1KdTreeCustomizableNode.html',1,'Ponca']]],
  ['kdtreecustomizablenode_3c_20index_2c_20nodeindex_2c_20datapoint_2c_20index_2c_20kdtreedefaultinnernode_3c_20nodeindex_2c_20datapoint_3a_3ascalar_2c_20datapoint_3a_3adim_20_3e_2c_20kdtreedefaultleafnode_3c_20index_2c_20index_20_3e_20_3e_9',['KdTreeCustomizableNode&lt; Index, NodeIndex, DataPoint, Index, KdTreeDefaultInnerNode&lt; NodeIndex, DataPoint::Scalar, DataPoint::Dim &gt;, KdTreeDefaultLeafNode&lt; Index, Index &gt; &gt;',['../classPonca_1_1KdTreeCustomizableNode.html',1,'Ponca']]],
  ['kdtreedefaultinnernode_10',['KdTreeDefaultInnerNode',['../structPonca_1_1KdTreeDefaultInnerNode.html',1,'Ponca']]],
  ['kdtreedefaultleafnode_11',['KdTreeDefaultLeafNode',['../structPonca_1_1KdTreeDefaultLeafNode.html',1,'Ponca']]],
  ['kdtreedefaultnode_12',['KdTreeDefaultNode',['../structPonca_1_1KdTreeDefaultNode.html',1,'Ponca']]],
  ['kdtreedefaulttraits_13',['KdTreeDefaultTraits',['../structPonca_1_1KdTreeDefaultTraits.html',1,'Ponca']]],
  ['kdtreedense_14',['KdTreeDense',['../structPonca_1_1KdTreeDense.html',1,'Ponca']]],
  ['kdtreedensebase_15',['kdtreedensebase',['../classPonca_1_1KdTreeDenseBase.html',1,'Ponca::KdTreeDenseBase&lt; Traits &gt;'],['../classPonca_1_1KdTreeDenseBase.html#a44dbbb76e78121fa0c4832ba190a98d1',1,'Ponca::KdTreeDenseBase::KdTreeDenseBase(PointUserContainer &amp;&amp;points)'],['../classPonca_1_1KdTreeDenseBase.html#a0755b6d9ec2855be13eaa5f173a894d2',1,'Ponca::KdTreeDenseBase::KdTreeDenseBase()=default']]],
  ['kdtreedensebase_3c_20kdtreedefaulttraits_3c_20datapoint_20_3e_20_3e_16',['KdTreeDenseBase&lt; KdTreeDefaultTraits&lt; DataPoint &gt; &gt;',['../classPonca_1_1KdTreeDenseBase.html',1,'Ponca']]],
  ['kdtreeknearestiterator_17',['KdTreeKNearestIterator',['../classPonca_1_1KdTreeKNearestIterator.html',1,'Ponca']]],
  ['kdtreeknearestquerybase_18',['KdTreeKNearestQueryBase',['../classPonca_1_1KdTreeKNearestQueryBase.html',1,'Ponca']]],
  ['kdtreenearestiterator_19',['KdTreeNearestIterator',['../classPonca_1_1KdTreeNearestIterator.html',1,'Ponca']]],
  ['kdtreenearestquerybase_20',['KdTreeNearestQueryBase',['../classPonca_1_1KdTreeNearestQueryBase.html',1,'Ponca']]],
  ['kdtreequery_21',['KdTreeQuery',['../classPonca_1_1KdTreeQuery.html',1,'Ponca']]],
  ['kdtreerangeiterator_22',['KdTreeRangeIterator',['../classPonca_1_1KdTreeRangeIterator.html',1,'Ponca']]],
  ['kdtreerangequerybase_23',['KdTreeRangeQueryBase',['../classPonca_1_1KdTreeRangeQueryBase.html',1,'Ponca']]],
  ['kdtreesparse_24',['KdTreeSparse',['../structPonca_1_1KdTreeSparse.html',1,'Ponca']]],
  ['kdtreesparsebase_25',['kdtreesparsebase',['../classPonca_1_1KdTreeSparseBase.html#a4a0c08913d66dfcb56f1d904a298a21a',1,'Ponca::KdTreeSparseBase::KdTreeSparseBase(PointUserContainer &amp;&amp;points, IndexUserContainer sampling)'],['../classPonca_1_1KdTreeSparseBase.html#a88bbd0abcddfeca97665028236fb9691',1,'Ponca::KdTreeSparseBase::KdTreeSparseBase(PointUserContainer &amp;&amp;points)'],['../classPonca_1_1KdTreeSparseBase.html#aca68b92e675a64d6fd185073db504d73',1,'Ponca::KdTreeSparseBase::KdTreeSparseBase()=default'],['../classPonca_1_1KdTreeSparseBase.html',1,'Ponca::KdTreeSparseBase&lt; Traits &gt;']]],
  ['kdtreesparsebase_3c_20kdtreedefaulttraits_3c_20datapoint_20_3e_20_3e_26',['KdTreeSparseBase&lt; KdTreeDefaultTraits&lt; DataPoint &gt; &gt;',['../classPonca_1_1KdTreeSparseBase.html',1,'Ponca']]],
  ['kernel_27',['kernel',['../example_python_ssc_page.html#pyssgl_cuda_kernel_sec',1,'Kernel'],['../example_cu_ssc_page.html#cu_ssgl_cuda_kernel_sec',1,'Kernel']]],
  ['kmax_28',['kmax',['../classPonca_1_1CurvatureEstimatorBase.html#a1be012e1ae52027cadcf8b71b1fb74ff',1,'Ponca::CurvatureEstimatorBase']]],
  ['kmaxdirection_29',['kmaxDirection',['../classPonca_1_1CurvatureEstimatorBase.html#aeca62f03a8d45a30277fe6e76c92f4da',1,'Ponca::CurvatureEstimatorBase']]],
  ['kmean_30',['kmean',['../classPonca_1_1CurvatureEstimatorBase.html#aeff60203146d08972a72c743dd036df4',1,'Ponca::CurvatureEstimatorBase::kMean()'],['../classPonca_1_1MongePatch.html#a1e9751313e09977e24df6ec35f40e394',1,'Ponca::MongePatch::kMean()']]],
  ['kmin_31',['kmin',['../classPonca_1_1CurvatureEstimatorBase.html#ad35407fad73f2a778a2058d689e079a4',1,'Ponca::CurvatureEstimatorBase']]],
  ['kmindirection_32',['kminDirection',['../classPonca_1_1CurvatureEstimatorBase.html#a0fa317770dd42fffaf2f5643ec03f527',1,'Ponca::CurvatureEstimatorBase']]],
  ['knearestindexquery_33',['KNearestIndexQuery',['../group__spatialpartitioning.html#structPonca_1_1KNearestIndexQuery',1,'Ponca']]],
  ['knearestindexquery_3c_20traits_3a_3aindextype_2c_20traits_3a_3adatapoint_3a_3ascalar_20_3e_34',['KNearestIndexQuery&lt; Traits::IndexType, Traits::DataPoint::Scalar &gt;',['../group__spatialpartitioning.html',1,'Ponca']]],
  ['knearestpointquery_35',['KNearestPointQuery',['../group__spatialpartitioning.html#structPonca_1_1KNearestPointQuery',1,'Ponca']]],
  ['knngraph_36',['knngraph',['../spatialpartitioning.html#spatialpartitioning_knngraph',1,'KnnGraph'],['../namespacePonca.html#ab7bf93ae8146ea5f4471c1d06fa8895e',1,'Ponca::KnnGraph']]],
  ['knngraphbase_37',['knngraphbase',['../classPonca_1_1KnnGraphBase.html#a7294b2f4e8983db302e2fac4777364d2',1,'Ponca::KnnGraphBase::KnnGraphBase()'],['../classPonca_1_1KnnGraphBase.html',1,'Ponca::KnnGraphBase&lt; Traits &gt;']]],
  ['knngraphdefaulttraits_38',['KnnGraphDefaultTraits',['../structPonca_1_1KnnGraphDefaultTraits.html',1,'Ponca']]],
  ['knngraphknearestquery_39',['KnnGraphKNearestQuery',['../classPonca_1_1KnnGraphKNearestQuery.html',1,'Ponca']]],
  ['knngraphrangeiterator_40',['KnnGraphRangeIterator',['../classPonca_1_1KnnGraphRangeIterator.html',1,'Ponca']]],
  ['knngraphrangequery_41',['KnnGraphRangeQuery',['../classPonca_1_1KnnGraphRangeQuery.html',1,'Ponca']]]
];
