var searchData=
[
  ['k1_0',['k1',['../group__fitting.html#a877d9ead3ac1045ebbd94d1045fc38c6',1,'Ponca::CurvatureEstimatorBase']]],
  ['k1direction_1',['k1Direction',['../group__fitting.html#afb9830d3cd98bbf9b4c715bd6c6875a8',1,'Ponca::CurvatureEstimatorBase']]],
  ['k2_2',['k2',['../group__fitting.html#a4be6423b13b5ffe0cef33cddbb7d7cfc',1,'Ponca::CurvatureEstimatorBase']]],
  ['k2direction_3',['k2Direction',['../group__fitting.html#a8dad959069ee07f91a51ddb44eed9218',1,'Ponca::CurvatureEstimatorBase']]],
  ['kappa_4',['kappa',['../group__fitting.html#af50e8af7862b3dcb185ff21c573fa784',1,'Ponca::GLSParam']]],
  ['kappa_5fnormalized_5',['kappa_normalized',['../group__fitting.html#abec25f5fc1914516c36082df250ee50e',1,'Ponca::GLSParam']]],
  ['kdtree_6',['KdTree',['../group__spatialpartitioning.html#classPonca_1_1KdTree',1,'Ponca']]],
  ['kdtree_3c_20datapoint_20_3e_7',['KdTree&lt; DataPoint &gt;',['../group__spatialpartitioning.html',1,'Ponca']]],
  ['kdtreeknearestindexquery_8',['KdTreeKNearestIndexQuery',['../classPonca_1_1KdTreeKNearestIndexQuery.html',1,'Ponca']]],
  ['kdtreeknearestiterator_9',['KdTreeKNearestIterator',['../group__spatialpartitioning.html#classPonca_1_1KdTreeKNearestIterator',1,'Ponca']]],
  ['kdtreeknearestpointquery_10',['KdTreeKNearestPointQuery',['../classPonca_1_1KdTreeKNearestPointQuery.html',1,'Ponca']]],
  ['kdtreenearestindexquery_11',['KdTreeNearestIndexQuery',['../classPonca_1_1KdTreeNearestIndexQuery.html',1,'Ponca']]],
  ['kdtreenearestiterator_12',['KdTreeNearestIterator',['../group__spatialpartitioning.html#classPonca_1_1KdTreeNearestIterator',1,'Ponca']]],
  ['kdtreenearestpointquery_13',['KdTreeNearestPointQuery',['../classPonca_1_1KdTreeNearestPointQuery.html',1,'Ponca']]],
  ['kdtreenode_14',['KdTreeNode',['../group__spatialpartitioning.html#structPonca_1_1KdTreeNode',1,'Ponca']]],
  ['kdtreequery_15',['KdTreeQuery',['../group__spatialpartitioning.html#classPonca_1_1KdTreeQuery',1,'Ponca']]],
  ['kdtreerangeindexquery_16',['KdTreeRangeIndexQuery',['../classPonca_1_1KdTreeRangeIndexQuery.html',1,'Ponca']]],
  ['kdtreerangeiterator_17',['KdTreeRangeIterator',['../group__spatialpartitioning.html#classPonca_1_1KdTreeRangeIterator',1,'Ponca']]],
  ['kdtreerangepointquery_18',['KdTreeRangePointQuery',['../classPonca_1_1KdTreeRangePointQuery.html',1,'Ponca']]],
  ['kmean_19',['kMean',['../group__fitting.html#a2806aae38a187798de67d5eb38771c50',1,'Ponca::CurvatureEstimatorBase::kMean()'],['../group__fitting.html#a577334b5f0eb551c969135e70b1d849e',1,'Ponca::MongePatch::kMean()']]],
  ['knearestindexquery_20',['KNearestIndexQuery',['../group__spatialpartitioning.html#structPonca_1_1KNearestIndexQuery',1,'Ponca']]],
  ['knearestindexquery_3c_20datapoint_3a_3ascalar_20_3e_21',['KNearestIndexQuery&lt; DataPoint::Scalar &gt;',['../group__spatialpartitioning.html',1,'Ponca']]],
  ['knearestpointquery_22',['KNearestPointQuery',['../group__spatialpartitioning.html#structPonca_1_1KNearestPointQuery',1,'Ponca']]]
];
