var searchData=
[
  ['query_213',['Query',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisknearest_3c_20datapoint_3a_3ascalar_20_3e_20_3e_214',['Query&lt; QueryInputIsIndex, QueryOutputIsKNearest&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisknearest_3c_20scalar_20_3e_20_3e_215',['Query&lt; QueryInputIsIndex, QueryOutputIsKNearest&lt; Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisnearest_3c_20datapoint_3a_3ascalar_20_3e_20_3e_216',['Query&lt; QueryInputIsIndex, QueryOutputIsNearest&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisnearest_3c_20scalar_20_3e_20_3e_217',['Query&lt; QueryInputIsIndex, QueryOutputIsNearest&lt; Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisrange_3c_20datapoint_3a_3ascalar_20_3e_20_3e_218',['Query&lt; QueryInputIsIndex, QueryOutputIsRange&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisrange_3c_20scalar_20_3e_20_3e_219',['Query&lt; QueryInputIsIndex, QueryOutputIsRange&lt; Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisposition_3c_20datapoint_20_3e_2c_20queryoutputisknearest_3c_20datapoint_3a_3ascalar_20_3e_20_3e_220',['Query&lt; QueryInputIsPosition&lt; DataPoint &gt;, QueryOutputIsKNearest&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisposition_3c_20datapoint_20_3e_2c_20queryoutputisnearest_3c_20datapoint_3a_3ascalar_20_3e_20_3e_221',['Query&lt; QueryInputIsPosition&lt; DataPoint &gt;, QueryOutputIsNearest&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisposition_3c_20datapoint_20_3e_2c_20queryoutputisrange_3c_20datapoint_3a_3ascalar_20_3e_20_3e_222',['Query&lt; QueryInputIsPosition&lt; DataPoint &gt;, QueryOutputIsRange&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['queryinput_223',['QueryInput',['../structPonca_1_1QueryInput.html',1,'Ponca']]],
  ['queryinput_3c_20datapoint_3a_3avectortype_20_3e_224',['QueryInput&lt; DataPoint::VectorType &gt;',['../structPonca_1_1QueryInput.html',1,'Ponca']]],
  ['queryinput_3c_20int_20_3e_225',['QueryInput&lt; int &gt;',['../structPonca_1_1QueryInput.html',1,'Ponca']]],
  ['queryinputbase_226',['QueryInputBase',['../structPonca_1_1QueryInputBase.html',1,'Ponca']]],
  ['queryinputisindex_227',['QueryInputIsIndex',['../structPonca_1_1QueryInputIsIndex.html',1,'Ponca']]],
  ['queryinputisposition_228',['QueryInputIsPosition',['../structPonca_1_1QueryInputIsPosition.html',1,'Ponca']]],
  ['queryoutputbase_229',['QueryOutputBase',['../structPonca_1_1QueryOutputBase.html',1,'Ponca']]],
  ['queryoutputisknearest_230',['QueryOutputIsKNearest',['../structPonca_1_1QueryOutputIsKNearest.html',1,'Ponca']]],
  ['queryoutputisknearest_3c_20datapoint_3a_3ascalar_20_3e_231',['QueryOutputIsKNearest&lt; DataPoint::Scalar &gt;',['../structPonca_1_1QueryOutputIsKNearest.html',1,'Ponca']]],
  ['queryoutputisnearest_232',['QueryOutputIsNearest',['../structPonca_1_1QueryOutputIsNearest.html',1,'Ponca']]],
  ['queryoutputisnearest_3c_20datapoint_3a_3ascalar_20_3e_233',['QueryOutputIsNearest&lt; DataPoint::Scalar &gt;',['../structPonca_1_1QueryOutputIsNearest.html',1,'Ponca']]],
  ['queryoutputisrange_234',['QueryOutputIsRange',['../structPonca_1_1QueryOutputIsRange.html',1,'Ponca']]],
  ['queryoutputisrange_3c_20datapoint_3a_3ascalar_20_3e_235',['QueryOutputIsRange&lt; DataPoint::Scalar &gt;',['../structPonca_1_1QueryOutputIsRange.html',1,'Ponca']]]
];
