var searchData=
[
  ['k_0',['k',['../classPonca_1_1KnnGraphBase.html#a88878dc3a1b39079a2d20c61c15fee6c',1,'Ponca::KnnGraphBase']]],
  ['kappa_1',['kappa',['../classPonca_1_1GLSParam.html#af50e8af7862b3dcb185ff21c573fa784',1,'Ponca::GLSParam']]],
  ['kappa_5fnormalized_2',['kappa_normalized',['../classPonca_1_1GLSParam.html#abec25f5fc1914516c36082df250ee50e',1,'Ponca::GLSParam']]],
  ['kdtree_3',['KdTree',['../structPonca_1_1KdTree.html',1,'Ponca']]],
  ['kdtreebase_4',['KdTreeBase',['../classPonca_1_1KdTreeBase.html',1,'Ponca']]],
  ['kdtreebase_3c_20kdtreedefaulttraits_3c_20datapoint_20_3e_20_3e_5',['KdTreeBase&lt; KdTreeDefaultTraits&lt; DataPoint &gt; &gt;',['../classPonca_1_1KdTreeBase.html',1,'Ponca']]],
  ['kdtreecustomizablenode_6',['KdTreeCustomizableNode',['../classPonca_1_1KdTreeCustomizableNode.html',1,'Ponca']]],
  ['kdtreecustomizablenode_3c_20index_2c_20nodeindex_2c_20datapoint_2c_20index_2c_20kdtreedefaultinnernode_3c_20nodeindex_2c_20datapoint_3a_3ascalar_2c_20datapoint_3a_3adim_20_3e_2c_20kdtreedefaultleafnode_3c_20index_2c_20index_20_3e_20_3e_7',['KdTreeCustomizableNode&lt; Index, NodeIndex, DataPoint, Index, KdTreeDefaultInnerNode&lt; NodeIndex, DataPoint::Scalar, DataPoint::Dim &gt;, KdTreeDefaultLeafNode&lt; Index, Index &gt; &gt;',['../classPonca_1_1KdTreeCustomizableNode.html',1,'Ponca']]],
  ['kdtreedefaultinnernode_8',['KdTreeDefaultInnerNode',['../structPonca_1_1KdTreeDefaultInnerNode.html',1,'Ponca']]],
  ['kdtreedefaultleafnode_9',['KdTreeDefaultLeafNode',['../structPonca_1_1KdTreeDefaultLeafNode.html',1,'Ponca']]],
  ['kdtreedefaultnode_10',['KdTreeDefaultNode',['../structPonca_1_1KdTreeDefaultNode.html',1,'Ponca']]],
  ['kdtreedefaulttraits_11',['KdTreeDefaultTraits',['../structPonca_1_1KdTreeDefaultTraits.html',1,'Ponca']]],
  ['kdtreedense_12',['KdTreeDense',['../structPonca_1_1KdTreeDense.html',1,'Ponca']]],
  ['kdtreedensebase_13',['KdTreeDenseBase',['../classPonca_1_1KdTreeDenseBase.html#a44dbbb76e78121fa0c4832ba190a98d1',1,'Ponca::KdTreeDenseBase::KdTreeDenseBase(PointUserContainer &amp;&amp;points)'],['../classPonca_1_1KdTreeDenseBase.html#a0755b6d9ec2855be13eaa5f173a894d2',1,'Ponca::KdTreeDenseBase::KdTreeDenseBase()=default'],['../classPonca_1_1KdTreeDenseBase.html',1,'Ponca::KdTreeDenseBase&lt; Traits &gt;']]],
  ['kdtreedensebase_3c_20kdtreedefaulttraits_3c_20datapoint_20_3e_20_3e_14',['KdTreeDenseBase&lt; KdTreeDefaultTraits&lt; DataPoint &gt; &gt;',['../classPonca_1_1KdTreeDenseBase.html',1,'Ponca']]],
  ['kdtreeknearestiterator_15',['KdTreeKNearestIterator',['../classPonca_1_1KdTreeKNearestIterator.html',1,'Ponca']]],
  ['kdtreeknearestquerybase_16',['KdTreeKNearestQueryBase',['../classPonca_1_1KdTreeKNearestQueryBase.html',1,'Ponca']]],
  ['kdtreenearestiterator_17',['KdTreeNearestIterator',['../classPonca_1_1KdTreeNearestIterator.html',1,'Ponca']]],
  ['kdtreenearestquerybase_18',['KdTreeNearestQueryBase',['../classPonca_1_1KdTreeNearestQueryBase.html',1,'Ponca']]],
  ['kdtreequery_19',['KdTreeQuery',['../classPonca_1_1KdTreeQuery.html',1,'Ponca']]],
  ['kdtreerangeiterator_20',['KdTreeRangeIterator',['../classPonca_1_1KdTreeRangeIterator.html',1,'Ponca']]],
  ['kdtreerangequerybase_21',['KdTreeRangeQueryBase',['../classPonca_1_1KdTreeRangeQueryBase.html',1,'Ponca']]],
  ['kdtreesparse_22',['KdTreeSparse',['../structPonca_1_1KdTreeSparse.html',1,'Ponca']]],
  ['kdtreesparsebase_23',['KdTreeSparseBase',['../classPonca_1_1KdTreeSparseBase.html#aca68b92e675a64d6fd185073db504d73',1,'Ponca::KdTreeSparseBase::KdTreeSparseBase()=default'],['../classPonca_1_1KdTreeSparseBase.html#a88bbd0abcddfeca97665028236fb9691',1,'Ponca::KdTreeSparseBase::KdTreeSparseBase(PointUserContainer &amp;&amp;points)'],['../classPonca_1_1KdTreeSparseBase.html#a4a0c08913d66dfcb56f1d904a298a21a',1,'Ponca::KdTreeSparseBase::KdTreeSparseBase(PointUserContainer &amp;&amp;points, IndexUserContainer sampling)'],['../classPonca_1_1KdTreeSparseBase.html',1,'Ponca::KdTreeSparseBase&lt; Traits &gt;']]],
  ['kdtreesparsebase_3c_20kdtreedefaulttraits_3c_20datapoint_20_3e_20_3e_24',['KdTreeSparseBase&lt; KdTreeDefaultTraits&lt; DataPoint &gt; &gt;',['../classPonca_1_1KdTreeSparseBase.html',1,'Ponca']]],
  ['kmax_25',['kmax',['../classPonca_1_1CurvatureEstimatorBase.html#a94235972fc3a63695413f7ce8dc479a1',1,'Ponca::CurvatureEstimatorBase']]],
  ['kmaxdirection_26',['kmaxDirection',['../classPonca_1_1CurvatureEstimatorBase.html#afcee7a07503a67e81ddde954982bfe00',1,'Ponca::CurvatureEstimatorBase']]],
  ['kmean_27',['kMean',['../classPonca_1_1MongePatch.html#a577334b5f0eb551c969135e70b1d849e',1,'Ponca::MongePatch::kMean()'],['../classPonca_1_1CurvatureEstimatorBase.html#a2806aae38a187798de67d5eb38771c50',1,'Ponca::CurvatureEstimatorBase::kMean() const']]],
  ['kmin_28',['kmin',['../classPonca_1_1CurvatureEstimatorBase.html#a96dffeac050d368bed883f03f9d7652b',1,'Ponca::CurvatureEstimatorBase']]],
  ['kmindirection_29',['kminDirection',['../classPonca_1_1CurvatureEstimatorBase.html#a68fd5de356c97aac92b3f11753d205f6',1,'Ponca::CurvatureEstimatorBase']]],
  ['knearestindexquery_30',['KNearestIndexQuery',['../group__spatialpartitioning.html#structPonca_1_1KNearestIndexQuery',1,'Ponca']]],
  ['knearestindexquery_3c_20traits_3a_3aindextype_2c_20traits_3a_3adatapoint_3a_3ascalar_20_3e_31',['KNearestIndexQuery&lt; Traits::IndexType, Traits::DataPoint::Scalar &gt;',['../group__spatialpartitioning.html',1,'Ponca']]],
  ['knearestpointquery_32',['KNearestPointQuery',['../group__spatialpartitioning.html#structPonca_1_1KNearestPointQuery',1,'Ponca']]],
  ['knngraph_33',['KnnGraph',['../namespacePonca.html#ab7bf93ae8146ea5f4471c1d06fa8895e',1,'Ponca']]],
  ['knngraphbase_34',['KnnGraphBase',['../classPonca_1_1KnnGraphBase.html#a7294b2f4e8983db302e2fac4777364d2',1,'Ponca::KnnGraphBase::KnnGraphBase()'],['../classPonca_1_1KnnGraphBase.html',1,'Ponca::KnnGraphBase&lt; Traits &gt;']]],
  ['knngraphdefaulttraits_35',['KnnGraphDefaultTraits',['../structPonca_1_1KnnGraphDefaultTraits.html',1,'Ponca']]],
  ['knngraphknearestquery_36',['KnnGraphKNearestQuery',['../classPonca_1_1KnnGraphKNearestQuery.html',1,'Ponca']]],
  ['knngraphrangeiterator_37',['KnnGraphRangeIterator',['../classPonca_1_1KnnGraphRangeIterator.html',1,'Ponca']]],
  ['knngraphrangequery_38',['KnnGraphRangeQuery',['../classPonca_1_1KnnGraphRangeQuery.html',1,'Ponca']]]
];
