var searchData=
[
  ['query_349',['Query',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisknearest_3c_20datapoint_3a_3ascalar_20_3e_20_3e_350',['Query&lt; QueryInputIsIndex, QueryOutputIsKNearest&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisknearest_3c_20scalar_20_3e_20_3e_351',['Query&lt; QueryInputIsIndex, QueryOutputIsKNearest&lt; Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisnearest_3c_20datapoint_3a_3ascalar_20_3e_20_3e_352',['Query&lt; QueryInputIsIndex, QueryOutputIsNearest&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisnearest_3c_20scalar_20_3e_20_3e_353',['Query&lt; QueryInputIsIndex, QueryOutputIsNearest&lt; Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisrange_3c_20datapoint_3a_3ascalar_20_3e_20_3e_354',['Query&lt; QueryInputIsIndex, QueryOutputIsRange&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisindex_2c_20queryoutputisrange_3c_20scalar_20_3e_20_3e_355',['Query&lt; QueryInputIsIndex, QueryOutputIsRange&lt; Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisposition_3c_20datapoint_20_3e_2c_20queryoutputisknearest_3c_20datapoint_3a_3ascalar_20_3e_20_3e_356',['Query&lt; QueryInputIsPosition&lt; DataPoint &gt;, QueryOutputIsKNearest&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisposition_3c_20datapoint_20_3e_2c_20queryoutputisnearest_3c_20datapoint_3a_3ascalar_20_3e_20_3e_357',['Query&lt; QueryInputIsPosition&lt; DataPoint &gt;, QueryOutputIsNearest&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['query_3c_20queryinputisposition_3c_20datapoint_20_3e_2c_20queryoutputisrange_3c_20datapoint_3a_3ascalar_20_3e_20_3e_358',['Query&lt; QueryInputIsPosition&lt; DataPoint &gt;, QueryOutputIsRange&lt; DataPoint::Scalar &gt; &gt;',['../structPonca_1_1Query.html',1,'Ponca']]],
  ['queryinput_359',['QueryInput',['../structPonca_1_1QueryInput.html',1,'Ponca']]],
  ['queryinput_3c_20datapoint_3a_3avectortype_20_3e_360',['QueryInput&lt; DataPoint::VectorType &gt;',['../structPonca_1_1QueryInput.html',1,'Ponca']]],
  ['queryinput_3c_20int_20_3e_361',['QueryInput&lt; int &gt;',['../structPonca_1_1QueryInput.html',1,'Ponca']]],
  ['queryinputbase_362',['QueryInputBase',['../structPonca_1_1QueryInputBase.html',1,'Ponca']]],
  ['queryinputisindex_363',['QueryInputIsIndex',['../structPonca_1_1QueryInputIsIndex.html',1,'Ponca']]],
  ['queryinputisposition_364',['QueryInputIsPosition',['../structPonca_1_1QueryInputIsPosition.html',1,'Ponca']]],
  ['queryoutputbase_365',['QueryOutputBase',['../structPonca_1_1QueryOutputBase.html',1,'Ponca']]],
  ['queryoutputisknearest_366',['QueryOutputIsKNearest',['../structPonca_1_1QueryOutputIsKNearest.html',1,'Ponca']]],
  ['queryoutputisknearest_3c_20datapoint_3a_3ascalar_20_3e_367',['QueryOutputIsKNearest&lt; DataPoint::Scalar &gt;',['../structPonca_1_1QueryOutputIsKNearest.html',1,'Ponca']]],
  ['queryoutputisnearest_368',['QueryOutputIsNearest',['../structPonca_1_1QueryOutputIsNearest.html',1,'Ponca']]],
  ['queryoutputisnearest_3c_20datapoint_3a_3ascalar_20_3e_369',['QueryOutputIsNearest&lt; DataPoint::Scalar &gt;',['../structPonca_1_1QueryOutputIsNearest.html',1,'Ponca']]],
  ['queryoutputisrange_370',['QueryOutputIsRange',['../structPonca_1_1QueryOutputIsRange.html',1,'Ponca']]],
  ['queryoutputisrange_3c_20datapoint_3a_3ascalar_20_3e_371',['QueryOutputIsRange&lt; DataPoint::Scalar &gt;',['../structPonca_1_1QueryOutputIsRange.html',1,'Ponca']]]
];
