name: Check formatting

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: RafikFarhad/clang-format-github-action@v6
        with:
          sources: "**/*.h,**/*.hpp,**/*.cpp"
          style: "file"
 
